/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeamEntry = IDL.Record({
  'teamName' : IDL.Text,
  'traits' : IDL.Vec(IDL.Text),
  'totalScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(TeamEntry)], ['query']),
  'resetLeaderboard' : IDL.Func([], [], []),
  'submitEntry' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeamEntry = IDL.Record({
    'teamName' : IDL.Text,
    'traits' : IDL.Vec(IDL.Text),
    'totalScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(TeamEntry)], ['query']),
    'resetLeaderboard' : IDL.Func([], [], []),
    'submitEntry' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };